### ISSUE TITLE
create_db.py TypeError: Won't implicitly convert Unicode to bytes; use .encode()

### ISSUE THREAD

**Issue by jed-frey** [jed-frey/DIGITS#1]
```(venv) root@i7:~/DIGITS# /root/venv3/bin/python /root/DIGITS/digits/tools/create_db.py /root/DIGITS/digits/jobs/20170110-190819-8908e60e40f68d09a78c358e/train.txt /root/DIGITS/digits/jobs/20170110-190819-8908e60e40f68d09a78c358e/train_db 256 256 --backend=lmdb --channels=3 --resize_mode=squash --mean_file=/root/DIGITS/digits/jobs/20170110-190819-8908e60e40f68d09a78c358e/mean.binaryproto --mean_file=/root/DIGITS/digits/jobs/20170110-190819-8908e60e40f68d09a78c358e/mean.jpg --shuffle --encoding=png
2017-01-10 22:22:29 [WARNING] removing existing database
2017-01-10 22:22:29 [DEBUG] 92 total lines in file
2017-01-10 22:22:29 [INFO ] 92 valid lines in file
2017-01-10 22:22:29 [DEBUG] Category 0 has 49 images.
2017-01-10 22:22:29 [DEBUG] Category 1 has 43 images.
Traceback (most recent call last):
  File "/root/DIGITS/digits/tools/create_db.py", line 792, in <module>
    hdf5_dset_limit=args['hdf5_dset_limit'],
  File "/root/DIGITS/digits/tools/create_db.py", line 294, in create_db
    mean_files, **kwargs)
  File "/root/DIGITS/digits/tools/create_db.py", line 367, in _create_lmdb
    _write_batch_lmdb(db, batch, images_written)
  File "/root/DIGITS/digits/tools/create_db.py", line 665, in _write_batch_lmdb
    lmdb_txn.put(key, datum.SerializeToString())
TypeError: Won't implicitly convert Unicode to bytes; use .encode()
```

This error only shows up in py-lmdb: https://github.com/dw/py-lmdb/blob/master/lmdb/cpython.c#L593

And as far as I can trace it is coming because the ```datum = caffe_pb2.Datum()``` is returning true as a Unicode object. (```PyUnicode_CheckExact```)

**Comment by jed-frey** [comment]
lmdb_txn.put(key, datum.SerializeToString())

```key``` needed to be encoded, not ```datum```.
