### ISSUE TITLE
TypeError:

### ISSUE THREAD

**Issue by jed-frey** [jed-frey/DIGITS#4]
Error when attempting to "Download Model" from a Models page.

```
Traceback (most recent call last):
  File "/home/jafrey/digits_venv/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jafrey/digits_venv/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/keg/Python/DIGITS/digits/webapp.py", line 82, in decorated
    return f(*args, **kwargs)
  File "/mnt/keg/Python/DIGITS/digits/model/views.py", line 267, in download
    info_io.write(info)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by seawei1993** [comment]
Did this problem is solved?

**Comment by jed-frey** [comment]
No.
