### ISSUE TITLE
A valid Caffe installation was not found on your system.

### ISSUE THREAD

**Issue by jed-frey** [jed-frey/DIGITS#9]
```
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "./resize_image.py", line 13, in <module>
    import digits.config  # noqa
  File "/projects/DIGITS/digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "/projects/DIGITS/digits/config/caffe.py", line 278, in <module>
    executable, version, flavor = load_from_path()
  File "/projects/DIGITS/digits/config/caffe.py", line 97, in load_from_path
    raise ValueError('Caffe executable not found in PATH')
ValueError: Caffe executable not found in PATH

```

**Comment by jed-frey** [comment]
Assuming [```build_caffe```](https://github.com/jed-frey/build_caffe) is extracted to ```/opt/caffe```

Temporarily:

    export PATH="/opt/caffe:$PATH"

Permanently, local, starting next shell:

    export 'PATH=/opt/caffe:$PATH' >> ~/.bashrc

Permanently, all users:

    echo 'export PATH=/opt/caffe/distribute/bin:$PATH' > /etc/profile.d/caffe.sh
